//interns
export const SET_INTERNS_COUNT = "SET_INTERNS_COUNT";
export const SET_INTERNS = "SET_INTERNS";
export const IS_FETCHING_INTERNS = "IS_FETCHING_INTERNS";
export const FETCHING_INTERNS_ERROR_MSG = "FETCHING_INTERNS_ERROR_MSG";

//tasks
export const SET_TASKS_COUNT = "SET_TASKS_COUNT";
export const SET_TASKS = "SET_TASKS";
export const IS_FETCHING_TASKS = "IS_FETCHING_TASKS";
export const FETCHING_TASKS_ERROR_MSG = "FETCHING_TASKS_ERROR_MSG";

//projects
export const SET_PROJECTS_COUNT = "SET_PROJECTS_COUNT";
export const SET_PROJECTS = "SET_PROJECTS";
export const IS_FETCHING_PROJECTS = "IS_FETCHING_PROJECTS";
export const FETCHING_PROJECTS_ERROR_MSG = "FETCHING_PROJECTS_ERROR_MSG";
