//interns
export const SET_INTERNS_COUNT = "SET_INTERNS_COUNT";
export const SET_INTERNS = "SET_INTERNS";
export const IS_FETCHING_INTERNS = "IS_FETCHING_INTERNS";
export const FETCHING_INTERNS_ERROR_MSG = "FETCHING_INTERNS_ERROR_MSG";
